apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entto-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/entto/manifests
    repoURL: https://github.com/SangYunLeee/argocd-enttolog.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
