apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: prometheus-grafana-stack
    repoURL: https://github.com/SangYunLeee/devops-manifest.git
    targetRevision: HEAD
