apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - directory:
      recurse: true
    path: prometheus-stack/helm
    repoURL: https://github.com/SangYunLeee/devops-package.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
