prometheus:
  image:
    repository: prom/prometheus
    tag: v2.45.0
  port: 9090
  nodePort: 32000
  nodeSelector:
    monitoring: "true"
  volumes:
    - name: data
      hostPath:
        path: /k8s/monitoring/prometheus/data
        type: DirectoryOrCreate

grafana:
  image:
    repository: sororiri/grafana
    tag: 5
  port: 3000
  nodePort: 32001
nodeExporter:
  image:
    repository: prom/node-exporter
    tag: v1.8.2
  port: 9100
  nodePort: 32002
slack:
  token: TOBE_UPDATED
