apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.grafana.nodePort }}
  type: NodePort
