volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: jenkins-data
    hostPath:
      path: /k8s/var/jenkins_home
      type: DirectoryOrCreate

ingress:
  enabled: true
  host: njenkins.entto.shop
  tls: true

namespace: deploy

nodeSelector:
  type: deploy

image:
  repository: sororiri/jenkins
  tag: 0.0.3
