apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: logs
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: fluent-bit
    helm:
      valueFiles:
      - $values/applications/common/logging/fluent-bit/fluent-bit/values.yaml
      - $values/applications/common/logging/fluent-bit/fluent-bit/values-custom.yaml
    repoURL: https://sangyunleee.github.io/argocd-enttolog/applications/common/logging/fluent-bit
    targetRevision: 0.43.0
  - ref: values
    repoURL: https://github.com/SangYunLeee/argocd-enttolog.git
    targetRevision: HEAD
