apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-application
  namespace: argocd
spec:
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 5
  source:
    path: applications/common/mysql
    repoURL: https://github.com/SangYunLeee/argocd-enttolog.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
