apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack-application
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/manifest
    repoURL: https://github.com/memomou/efk-stack.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
